### ISSUE TITLE
java.lang.IllegalStateException: Already resumed

### ISSUE THREAD

**Issue by ch4rl3x** [ch4rl3x/billing-suspend#35]
```
java.lang.IllegalStateException: Already resumed
        at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:44)
        at de.charlex.billing.BillingHelper$startConnectionIfNecessary$2$1.onBillingServiceDisconnected(BillingHelper.kt:59)
        at com.android.billingclient.api.zzaf.onServiceDisconnected(com.android.billingclient:billing@@4.0.0:4)
        at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:2059)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2074)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7727)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

**Comment by eywinapp** [comment]
Hi, is there any progress with that issue? I searched but couldn't find any results.

**Comment by ch4rl3x** [comment]
> Hi, is there any progress with that issue? I searched but couldn't find any results.

No progress... I have not had time yet
